### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by pilz97** [addaleax/lzma-native#110]
Hi,

I wanted to install @deployjs/grunt-build, the command fails with:
npm ERR! code 1
npm ERR! path D:\Development\Git\kellnerapp-angular\node_modules\lzma-native
npm ERR! command failed

That's why i tried to run npm i lzma-native, but i get the same error here:
![image](https://user-images.githubusercontent.com/42172207/113671445-a1574f00-96b6-11eb-9652-886add640403.png)

Does anyone has an idea?

**Comment by addaleax** [comment]
You may want to share the **full** output if you want somebody to be able to help you.

**Comment by pilz97** [comment]
Hi @addaleax, thank you for your answer.

here is the full output:
D:\Development\Git\kellnerapp-angular>npm i lzma-native
npm ERR! code 1
npm ERR! path D:\Development\Git\kellnerapp-angular\node_modules\lzma-native
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@12.13.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.0 found at "C:\Users\stefan.pilz.APRO\AppData\Local\Programs\Python\Python37\python.exe"
npm ERR! gyp info find VS using VS2019 (16.9.31025.194) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\stefan.pilz.APRO\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'D:\\Development\\Git\\kellnerapp-angular\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Development\\Git\\kellnerapp-angular\\node_modules\\lzma-native\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Development\\Git\\kellnerapp-angular\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\stefan.pilz.APRO\\AppData\\Local\\node-gyp\\Cache\\12.13.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\stefan.pilz.APRO\\AppData\\Local\\node-gyp\\Cache\\12.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\Development\\Git\\kellnerapp-angular\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\stefan.pilz.APRO\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.13.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\Development\\Git\\kellnerapp-angular\\node_modules\\lzma-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\Development\\Git\\kellnerapp-angular\\node_modules\\lzma-native\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_path in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (D:\Development\Git\kellnerapp-angular\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Development\\Git\\kellnerapp-angular\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Development\Git\kellnerapp-angular\node_modules\lzma-native
npm ERR! gyp ERR! node -v v12.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by addaleax** [comment]
What’s your npm version? Can you install this if you use Node.js 14?

**Comment by pilz97** [comment]
NPM Version 7.8.0

When i update to node 14 my angular build fails, that's why i am using version 12.13.0

**Comment by addaleax** [comment]
Maybe it’s an npm-7-specific thing? There were a lot of changes in npm 7 that might affect this

**Comment by pilz97** [comment]
@addaleax thank you very much!
You were right, i just downgraded to npm 6.14.12 and now i can install  @deployjs/grunt-build

Thank you!!
