### ISSUE TITLE
Connection refused to node-pre-gyp.addalex.net

### ISSUE THREAD

**Issue by PaulSzymanski** [addaleax/lzma-native#114]
My ci pipeline suddenly greets me with an error:

```
node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-x64.tar.gz
node-pre-gyp WARN Hit error connect ECONNREFUSED 51.75.72.12:443 
```

My build node has no python installed. So it can not compile the dependency from source.
@addaleax did you misconfigure your DNS or server?

Not sure if this is the right place to submit this issue...

**Comment by addaleax** [comment]
Looks like the webserver crashed spontaneously, thanks for the ping. (I thought I had set it to automatically respawn when it crashes, but…?)

In any case, this is restarted, and newer versions of this package also don’t try to make any remote connections at all, so making people upgrade is also a good solution here. :)

Thank you!

**Comment by PaulSzymanski** [comment]
Thanks for resolving it so quickly 🙂 unfortunately the server seems down again 🙁 

Yes, upgrading would be great. I am depending on lzma-native via electron-rebuild. I think they will upgrade in their next major release (https://github.com/electron/electron-rebuild/issues/356).

**Comment by KingDaveTheBest** [comment]
Hi, the server is down again, or is still down from earlier.

Thanks!

**Comment by erikian** [comment]
Looks like it's down again, I've been getting the same error as @PaulSzymanski since yesterday.

**Comment by dpilarsk** [comment]
Hello @addaleax it seems the server has crashed again :/ (https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-win32-x64.tar.gz)

**Comment by zjufishboy** [comment]
@addaleax sorry,but it seems that the website is down again 😭😭😭😭
