### ISSUE TITLE
cant download prebuilt binaries

### ISSUE THREAD

**Issue by pplonski** [addaleax/lzma-native#116]
First of all, thank you for this package! I'm using it in electron app.

Yesterday and today I'm experiencing problems with downloading:
```
node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@14.17.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ECONNREFUSED 51.75.72.12:443
```

Is it some server problem? Thank you!

**Comment by pplonski** [comment]
Closing the issue. It is working currently.

Is there any way to help you to prevent such server down time?

**Comment by addaleax** [comment]
@pplonski You can update to the latest version of lzma-native, which doesn’t require network access at all. In the long run, that’s the solution here.
