### ISSUE TITLE
lzma native prebuilds not accessible

### ISSUE THREAD

**Issue by jjason685** [addaleax/lzma-native#122]
Seems like the prebuilds aren't able to be fetched, and building locally is erroring out on our build machine, any thoughts?

https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-darwin-x64.tar.gz the respective link it is trying to fetch the prebuilt from

**Comment by mrthorne** [comment]
Likewise, I think we are seeing a similar issue that started overnight sometime between 12/28/21@ 3pm PST (last successful pull) and 12/29/21 @ 9am PST.

`node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@10.24.0`
`node-pre-gyp WARN Hit error connect ECONNREFUSED 51.75.72.12:443`

**Comment by jjason685** [comment]
I was using electron-rebuild and updated the module, if you directly depend on lzma-native just update the module, if it's a dependency of another module you're using try to update that as well; worked great for me.

**Comment by mrthorne** [comment]
That's actually the same module we are experiencing this problem with (electron-rebuild), but updating that forced us to update node to 12.x, which has trickle-led to other problems.  The hope was in the meantime to resolve this issue for now to punt on all these downstream changes.  That said, glad you're at least back up and running @jjason685 !
