### ISSUE TITLE
v8.0.6 is missing at npm

### ISSUE THREAD

**Issue by Kikobeats** [addaleax/lzma-native#129]
![CleanShot 2022-01-18 at 12 13 20@2x](https://user-images.githubusercontent.com/2096101/149926960-e5657509-6191-446f-a9b9-ad56646002fb.png)

Looks like you forgot to run `npm publish` command

**Comment by addaleax** [comment]
yeah thank you for reminding me what i’m currently working on :unamused:

**Comment by Kikobeats** [comment]
I don't follow; the version is still not published, what's the problem there?

**Comment by addaleax** [comment]
@Kikobeats It means that I’m taking the time to do this release and fix CI so that *you* can have a fixed version of this library as soon as possible, and that it’s annoying to be poked about something that I’m already actively working on.

**Comment by addaleax** [comment]
@Kikobeats 8.0.6 is out now – thank you for your patience!

**Comment by Kikobeats** [comment]
appreciated the effort, but I'm still experimenting the same issue:

```
❯ npm i lzma-native@8.0.6

up to date in 895ms

~/Projects/microlink/ffprobe master*
❯ npm run postinstall

> @microlink/ffprobe@1.0.3 postinstall
> node scripts/postinstall.js

dyld[75780]: missing symbol called
fish: Job 1, 'npm run postinstall' terminated by signal SIGABRT (Abort)

~/Projects/microlink/ffprobe master*
❯ cat node_modules/lzma-native/package.json  | grep version
  "version": "8.0.6",
```
