### ISSUE TITLE
npm install from package.json not working on all systems

### ISSUE THREAD

**Issue by zuspan** [addaleax/lzma-native#18]
I have lzma-native in my package.json file on my node app: 
`"lzma-native": "~1.3.1"`

It loads fine when I push my repo to heroku. However, if I clone the repository locally (on mac) and `npm install`, it does not install the binding folder and perhaps other elements, which forces my app to error.

I'm not a total node expert, so perhaps this is my mistake?..please advise. Thanks!

**Comment by zuspan** [comment]
Here's the error from the console:

[console_error.txt](https://github.com/addaleax/lzma-native/files/265041/console_error.txt)

if I run npm install outside of a package.json on my mac machine, it installs fine....hmmm.

**Comment by addaleax** [comment]
Hi! The thing here is that `npm install`, without any arguments, does several things that other versions of that command (like your typical `npm install dependency-foobar`) do not:

- It installs all dependencies, including `devDependencies`
- It runs the `prepublish` script
- It runs the `install` script, which usually creates the bindings/ folder by downloading a pre-built binary or compiling the source

The `prepublish` script for this package currently uses the `7z` package manager to extract some files that are needed for compiling on Windows from an archive, to make sure that they are included when publishing a new version. [Here’s](https://github.com/addaleax/lzma-native/blob/master/package.json#L40) the line responsible for that – if you remove it, you should find that installing the library works for you.

Let me know if this works for you, and if a permanent solution would be important for you. I’ll definitely think about this, too.

> I'm not a total node expert, so perhaps this is my mistake?..please advise. Thanks!

Not being an expert is perfectly normal, and I’m glad to help!

**Comment by zuspan** [comment]
Thanks so much for getting back to me so quickly. I'm building a node app that uses lzma-native as a dependency - so if running the `npm install` command, which then accesses my app's package.json file, could successfully install lzma-native regardless of platform without special arguments/flags, that would be ideal. Thank you for this workaround though. I will see if there's a way to exclude this prepublish script from within my app's package.json file...hmmm....

**Comment by addaleax** [comment]
@zuspan If you run `npm install` in the directory with the package.json from *your* project, the prepublish script should not get triggered, I think? Normally, running `npm install` in a directory cloned from git means that you want to start hacking on the code in it.

**Comment by zuspan** [comment]
1) I clone my own repository. 
2) I `cd` to the root directory of my repository, where my package.json file resides. 
3) I then run `npm install` to install the node dependencies required by my app (from my package.json file). 

On my mac, this process does trigger the prepublish script, which throws the error for lzma-native.

Is that what you mean?

**Comment by addaleax** [comment]
Huh, that’s weird… running `npm install` outside of `lzma-native` should most certainly not trigger the prepublish script.

When I create a new directory and only place the following `package.json` in it:
```js
{
  "dependencies": {
    "lzma-native": "*"
  }
}
```
then running `npm install` does run the `install` script (like it should) but not the `prepublish` one… am I misunderstanding you or is this actually different for you? If so, what npm/node versions are you using (`npm -v`/`node -v` output)?

**Comment by zuspan** [comment]
OK - so when I recreate the isolated one-package json file as you did, it installs. When I run the full package.json file on my app, where lzma-native is one package among many, it doesn't.

It seems another package (`v8-debug`) requires an older version of `node-pre-gyp` (0.4.6), which throws an error and fails. As this package is required for lzma-native, perhaps that's the issue.

I will try a workaround...and will look through that package's issues. Thanks again for your help!

**Comment by addaleax** [comment]
Okay, if this is interference from other packages, then this is probably something that should not be considered a *bug* in this repository… I’m planning to publish a new version of lzma-native today with a fix for this anyway (see the commit that github linked above) , so you probably don’t have to look around a lot.

Running CI usually takes a while, though, so you may have to wait 2 hours or so. :smile:

**Comment by zuspan** [comment]
great. I will close this issue. And thanks again!

**Comment by addaleax** [comment]
@zuspan Just published a new version to npm. Could you check if the problem still exists, and reopen this issue if it does?

**Comment by zuspan** [comment]
the new version `1.4.0` still does not install the binding folder...it could still be an interaction with another package, but I'm not sure. Again - it compiles well on heroku, but not on my local mac. hmmm...

**Comment by addaleax** [comment]
How exactly does it fail? I can’t really believe it’s still the prepublish script. Do you have an `npm-debug.log` from the `npm install`? Could you upload it? That stuff is usually really helpful for debugging.

**Comment by zuspan** [comment]
So there is no specific error now with `npm install`, but when I run my app locally via `grunt`, it throws an error and crashes because it can't find the binding folder in the lzma-native node_module directory (as it is not created with `npm install`). I have attached a [somewhat redacted] npm-debug.log of my whole app. The error from the console when I run the app locally (via `grunt`) is below. Let me know how else I can help!

`Error: Cannot find module '/Users/[FOLDER REDACTED]/node_modules/lzma-native/binding/lzma_native.node'`
[[PARTIALLY REDACTED] npm-debug.log.txt](https://github.com/addaleax/lzma-native/files/266941/PARTIALLY.REDACTED.npm-debug.log.txt)

**Comment by addaleax** [comment]
> ``104856 verbose stack Error: v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build` ``

I think installing lzma-native fails because npm doesn’t even get there, it fails while installing `v8-debug`. Can you maybe verify that just running `npm install v8-debug` fails and/or that just running `lzma-install` works?

**Comment by addaleax** [comment]
@zuspan Does https://github.com/node-inspector/v8-debug/issues/7#issuecomment-154450807 help you/are there outdated dependencies in that general area as reported by `npm outdated`?

**Comment by zuspan** [comment]
that comment totally solved it! you were correct - `v8-debug` failed before getting to `lzma-native`. Thanks so much! Sorry to bother you with this...

**Comment by addaleax** [comment]
No problem, glad to help! :)

**Comment by zuspan** [comment]
also - in case you're curious, here's the project I'm using `lzma-native` in: www.kokowa.co. It's a project that enables anyone to be able to create in 3D/VR without prior modeling or programming skills. `lzma-native` helps with serving compressed assets to the client.

**Comment by addaleax** [comment]
Yep, I’m definitely curious – it’s always amazing to see who uses this library! What client-side counterpart are you using there? I’ve used https://github.com/nmrugg/LZMA-JS in the past and found it to be quite useful, but think this is some other derivative/port of the original LZMA SDK?

**Comment by zuspan** [comment]
yup - that's the one I'm using. It currently works off of strings, but I'm hoping to write a streaming client-side version soon for direct to/from byte. I need to look more at the client side - haven't in a few months. will let you know what I end up with next...this was the only lzma package I could find that had a bower implementation...

**Comment by addaleax** [comment]
Heh, yeah, I had written Uint8Array support for that but it’s currently queued in the v3 branch over there. Feel free to take a look at it/try it out, I’ve been using that in production for a while now.

**Comment by zuspan** [comment]
will do! thanks for the tip....
