### ISSUE TITLE
Multi-threaded compression

### ISSUE THREAD

**Issue by albertdb** [addaleax/lzma-native#20]
XZ utils allow multithreaded compression through `-T [0..N]` switch (being 0 the value to create as many threads as CPU cores), which makes a huge difference in compression time on multicore systems.

Does this library allow something similar?

Thank you.

**Comment by addaleax** [comment]
Not yet, but it’s something that I have in the back of my head. It probably shouldn’t be too hard to implement it, and I definitely see the benefits one can gain from it.

**Comment by addaleax** [comment]
```
$ npm publish
+ lzma-native@1.5.0
```

Done! :)

**Comment by albertdb** [comment]
Thank you very much. I'll try it later today.
