### ISSUE TITLE
issues building 32-bit version on 64 bit machine windows

### ISSUE THREAD

**Issue by leshow** [addaleax/lzma-native#22]
I have an electron application that I've built other native modules for, I am distributing a 32-bit application, from a 64-bit installation of windows 7.

essentially, the build goes fine 
```
npm install lzma-native --arch=ia32
electron-rebuild #with headers set to ia32
```

I've build like this for the node-keytar project and things went well. 

the issue happens when I start up my application after I've imported the built module, i get the dreaded
```
%1 is not a valid Win32 application
```

meaning that the 64-bit version of the library was likely built and not the 32-bit.

do you have any insight into this?

**Comment by addaleax** [comment]
Can you try doing something like `node-pre-gyp clean install --runtime=electron --target=[electron version] --target_arch=ia32`? It’s the support for pre-built binaries that appears to be getting in the way here.

I know that’s about what nw.js users do, and I know it should be very similar with electron. Also, feel free to ping me on Freenode (I’m addaleax there, too) about this, sometimes that’s a bit easier for investigating issues like this.

**Comment by leshow** [comment]
It is indeed the pre-gyp that appears to be breaking things. 

where should I run that command from? i assume i have to have node-pre-gyp installed from npm in order to do that?

**Comment by addaleax** [comment]
> i ran the command from the lzma-native dir in node_modules:

Looks good – if there were no further errors, could you add `--fallback-to-build` to the command line?

**Comment by leshow** [comment]
the build runs fine after adding that command, however on startup electron cant find the module

```
The specified module could not be found. 
\\?\C:\Users\test\electron-lobby\build\node_modules\lzma-native\binding\lzma_native.node
```

I was able to get it to build however, by running:

```
export npm_config_target=1.2.1
export npm_config_arch=ia32
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_runtime=electron
export npm_config_build_from_source=true
npm install lzma-native
```

this runs fine when starting electron from the command prompt, however when packaging an application-- it is not able to find the module (even though it is all contained in the asar file)
 
I understand you probably can't help with this, thanks for your time.

I do have a final question though: the lzma-native directory in node_modules after build is over 30mb, this is roughly 3 times the size of my entire application. Why is the build so big? 

The largest offenders appear to be the node_modules dir inside of lzma-native at 15mb and build/Release at ~12mb

by contrast, I have a C executable (granted just the lzma decompress lib) that is 60kb.

**Comment by addaleax** [comment]
> this runs fine when starting electron from the command prompt, however when packaging an application-- it is not able to find the module (even though it is all contained in the asar file)

Can you require the full path of the `.node` file manually? Do you rename the resulting `.exe`?

> The largest offenders appear to be the node_modules dir inside of lzma-native at 15mb

`node-pre-gyp` is a likely candidate as a huge dependency, and that is a known issue of theirs. Unfortunately, without it, installing on Windows without a compiler toolchain is virtually impossible. See e.g. https://github.com/mapbox/node-pre-gyp/issues/191

> build/Release at ~12mb

You’ll have to look inside of it to know what’s going on, but you can safely delete that after compiling.

**Comment by leshow** [comment]
> Can you require the full path of the .node file manually? Do you rename the resulting .exe?

manually requiring the .node file doesn't appear to work either, even though I can see it in the node_modules directory.

`var lzma = require('lzma-native/build/Release/lzma_native.node');` is what I tried, and that file certainly exists.

**Comment by addaleax** [comment]
You’ll need to require the file in `binding/`, not in `build/Release/…`, because on Windows the shared liblzma library is necessary (`binding/liblzma.dll` exists, right?).

**Comment by leshow** [comment]
It does not, there is no liblzma.dll in binding. the .dll appears to be `ideps/bin_i686/`

**Comment by addaleax** [comment]
Huh. That should happen as part of the build process (is there any error output?), but you can also copy the file manually of course.

**Comment by leshow** [comment]
OK, so with the dll copied in there, I can require lzma_native.node and the application runs like it did with a regular require('lzma-native')... however when the application is bundled in an asar, I am still getting the 

```
The specified module could not be found \\?\C:\Users\test\AppData\Local\Temp\F74B.tmp.node
```
 error, unpacking the asar reveals that the directory structure of lzma-native is identical, the copied dll file is there and everything.

**Comment by addaleax** [comment]
Ah, electron seems to do something weird when requiring the native module here (I think it copies it to some other location?)… I’ll look into that, but you can probably get around it by copying the liblzma.dll to a directory in the current `PATH` (and/or create a temp directory that you add to the current `PATH`).

**Comment by leshow** [comment]
That may get the packaged program working on this machine, but I can't redistribute an application that requires the user to have liblzma.dll in their path. Still, if you find out where it needs to go, I'd be curious.

speaking of redistributing, what are the files here that are absolutely necessary to be included in a final build if I was to package this up in an application. is it just the contents of the binding/ dir and the package.json in the lzma-native root?

**Comment by addaleax** [comment]
> but I can't redistribute an application that requires the user to have liblzma.dll in their path

I completely get that. :) I’ll look into how electron handles these cases exactly (I’m also pretty curious right now), so I’d suggest creating a temp directory, copying the appropriate liblzma.dll there and explicitly adding that directory to `process.env.PATH`.

> what are the files here that are absolutely necessary to be included in a final build if I was to package this up in an application

The `index.js` is necessary, too, to provide the streaming layer on top of the native code invocations. `node-pre-gyp` is used as a dependency there to look up the path of the native addon, but you can apply a patch if you know the binding file path for certain.

**Comment by leshow** [comment]
Sounds good, I appreciate the time you've taken to respond to my questions.

**Comment by leshow** [comment]
Your library is the only native lzma module that compiles properly for electron and runs without errors BTW, and it's *so* close to being able to be included and distributed. It would be great if we could push it over the finish line, let me know if you need anything.

**Comment by addaleax** [comment]
I know that this native addon stuff, especially on Windows and for non-Node environments, is a major buzzkill… it doesn’t sound like it would help you a lot, but if you’re looking for other people to install your code locally, I can try and see whether I can get pre-build binaries for electron together.

I already did that for nw.js, and it seems to work (you can take a look at https://github.com/gamejolt/gamejolt/blob/39457d01e5b2926bbdd98736914fc329e67a5690/tasks/client.js), it’s just not something that particularly many people make use of.

Also… that “missing” liblzma.dll is the only thing that’s standing in the way of distributing right now, right?

**Comment by leshow** [comment]
with the liblzma.dll added to the path, the packaged application works just fine, so yes that is what is standing it the way of redistributing this. 

electron releases pretty rapidly, and I think you need to build the headers against the version of node that ships with electron (at least, thats what i did to get this module to work on my VM). So unless you want to rebuild and distribute binaries for your module every time electron updates it's node version, it's a lot easier to just let developers build it with node-gyp. I use a popular native module called `keytar` https://github.com/atom/node-keytar that abstracts password toolchain on all platforms, and it was very easy to build.  

In this case, the fact this module uses node-pre-gyp makes it easier for node applications to use lzma-native, but very difficult for developers looking to use the module in anything else, at least, so far as I can tell.

Still, that doesn't really explain why the dll seems to be available when running from the cli and not available when packaged? unless somehow things are implicitly included in the path when run from the cli?

**Comment by addaleax** [comment]
> with the liblzma.dll added to the path, the packaged application works just fine, so yes that is what is standing it the way of redistributing this. 

I’m building this addon with a static liblzma right now. Shouldn’t be too hard™, but that’s always what you think before you try it.

> electron releases pretty rapidly, and I think you need to build the headers against the version of node that ships with electron

Yeah, I think so, too.

> Still, that doesn't really explain why the dll seems to be available when running from the cli and not available when packaged

What I imagine is happening is that, in order to `require()` a native addon, electron extracts the `.node` bindings file from the package into a temporary folder and requires that one. The Windows DLL loader won’t be able to find the corresponding `liblzma.dll` (which is usually in the same directory as the `.node` file), and thus report that an something along the lines of an “file not found” error back to electron.

**Comment by addaleax** [comment]
> Shouldn’t be too hard™, but that’s always what you think before you try it.

Update: It is hard, Windows DLL import/export “magic” strikes again. I still want to get that working, but it might take a bit.

If your packaged application can create temporary directories and copy files from the package itself to there, then the workaround in https://github.com/addaleax/lzma-native/issues/22#issuecomment-230327945 should work just fine…

**Comment by leshow** [comment]
HA! It looks like if I include the liblzma.dll in the main directory of my application, electron is able to find it. When you package an electron app (typically with electron-packager) it has the structure:

```
app/
       electron.exe
       msvcp120.dll
       libEGL.dll
       ...
       resources/ 
                        app.asar
                        electron.asar
```

including liblzma.dll in the main app dir works.

**Comment by addaleax** [comment]
Does electron extract its entire package to some temp location before starting up? If so, that makes perfect sense.

**Comment by leshow** [comment]
Yep! it works just fine with liblzma.dll in the electron dir. I was able to remove most of the cruft from the lzma-native node_modules/ dir so it only adds 2mb to my final application size instead of 30 too.

I'm not sure what electron does during startup, it does create a few directories though. namely in %APPDATA%  / XDG_HOME on Linux.

**Comment by leshow** [comment]
Thank you again for your help, if you need any help testing on electron in the future, let me know. I'll close this ticket.

**Comment by addaleax** [comment]
Yup, will do! And feel free to contact me here or on IRC if anything else comes up. :)

**Comment by leshow** [comment]
where can i find you on IRC?

**Comment by addaleax** [comment]
`addaleax` on Freenode :)

**Comment by Nadeve** [comment]
Hey @addaleax , I'm still getting the same `%1 is not a valid Win32 application` issue using node v8.1.4;
I've tried running `node-pre-gyp clean install --runtime=electron --target-1.6.6 --fallback-to-build`, which results in an `lzma_native.node` file, which ubuntu 16.04 claims is a win32 binary (using the `file` command). 

I've opened a StackOverflow [thread](https://stackoverflow.com/questions/45167026/problems-compiling-etcher-fork-using-electron-builder) with more implementation-specific detail. Thanks :)

**Comment by addaleax** [comment]
@Nadeve Sorry to hear that :/

a) I assume it’s just a typo and maybe completely irrelevant, but what happens if you change `--target-1.6.6` to `--target=1.6.6`?
b) Can you override the target architecture manually with `--target_platform=win32 --target_arch=ia32` (or `--target_arch=x64`, depending on which one you actually need)? Does that help?
c) Your SO post says Ubuntu reports it as a “32-bit LSB shared object” – is that the file from the Windows build, or a different one?

**Comment by Nadeve** [comment]
Thanks for the reply @addaleax,
After some digging in Etcher's docs it seems as if they don't support cross-building,
so this 'bug' might be Etcher messing with the build somehow.

Will keep you posted as I try compiling from windows :)

**Comment by Nadeve** [comment]
Indeed, it was probably an Etcher problem, as I've just successfully compiled it under windows.
Sorry for the trouble!
