### ISSUE TITLE
Sudden LZMA_PROG_ERROR 

### ISSUE THREAD

**Issue by jviotti** [addaleax/lzma-native#25]
Hi,

I'm starting to encounter the following issue in Etcher, after a `lama-native` version upgrade I believe:

```
tracker.js:10 LZMA_PROG_ERROR: Programming error
    at Error (native)
    at LZMAStream.Stream.autoDecoder (/Users/jviotti/Projects/resin/etcher/node_modules/lzma-native/index.js:295:15)
    at exports.createStream (/Users/jviotti/Projects/resin/etcher/node_modules/lzma-native/index.js:317:16)
    at Object.exports.createDecompressor (/Users/jviotti/Projects/resin/etcher/node_modules/lzma-native/index.js:330:10)
    at Object.application/x-xz (/Users/jviotti/Projects/resin/etcher/node_modules/etcher-image-stream/lib/handlers.js:103:40)
    at /Users/jviotti/Projects/resin/etcher/node_modules/etcher-image-stream/lib/index.js:71:26
    at tryCatcher (/Users/jviotti/Projects/resin/etcher/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/jviotti/Projects/resin/etcher/node_modules/bluebird/js/release/method.js:39:29)
    at Object.exports.getFromFilePath (/Users/jviotti/Projects/resin/etcher/node_modules/etcher-image-stream/lib/index.js:64:22)
    at Object.exports.getEstimatedFinalSize (/Users/jviotti/Projects/resin/etcher/node_modules/etcher-image-stream/lib/index.js:100:18)
    at electron.remote.dialog.showOpenDialog (/Users/jviotti/Projects/resin/etcher/lib/gui/os/dialog/services/dialog.js:74:21)
    at CallbacksRegistry.apply (/Users/jviotti/Projects/resin/etcher/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Users/jviotti/Projects/resin/etcher/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:243:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7) undefined
```

As far as I can see, the issue only seems to happen when running this module on Electron.

The error is thrown by `lzma.createDecompressor()`, which I'm simply using like this:

```js
return Bluebird.props({
  stream: fs.createReadStream(file),
  size: fs.statAsync(file).get('size'),
  transform: Bluebird.resolve(lzma.createDecompressor())
});
```

If you want to reproduce this on Etcher itself, there is a small guided to run Etcher locally (see https://github.com/resin-io/etcher/blob/master/docs/CONTRIBUTING.md#running-locally). Checkout the `upgrade/image-stream` branch. The error is thrown as soon as you select a `.xz` image.

The error doesn't seem to happen on v1.4.

**Comment by addaleax** [comment]
Hi, thanks for the reports, I’ll be looking into these today!

**Comment by jviotti** [comment]
Thanks a lot! Let me know if I can provide anything else (information, testing time, etc)!

**Comment by addaleax** [comment]
I will! I can reproduce the error here, so it might not be too hard to figure out what’s going on. :)

**Comment by addaleax** [comment]
Ah, okay, I got it. Electron 1.2.6 ships the headers for V8 5.1, while Node v6 is at V8 5.0; the API has been backwards-compatible, but the ABI hasn’t (we’re actually putting quite a bit of work into an ABI-compatible upgrade to V8 5.1 in Node core).

I have a `nodedir` setting in my `~/.npmrc`, disabling that and then running the setup script again worked for me… lmk if that works (or even applies to you), I guess?

And btw, forcing the build to be done with the same version as Node is a bit strict – ABI/API compatibility is guaranteed over an entire major node version.

**Comment by addaleax** [comment]
Also, this shouldn’t be related to the version bump in lzma-native… does that sound plausible to you?

I’m pretty sure the root cause of these problems is that the V8 shipped with Electron has a different offset for the field that distinguishes different kinds of “oddball” objects (`undefined`, `null`, `false`, `true`) than the V8 in Node v6, not some change in this repo.

**Comment by jviotti** [comment]
Hi @addaleax 

> Ah, okay, I got it. Electron 1.2.6 ships the headers for V8 5.1, while Node v6 is at V8 5.0; the API has been backwards-compatible, but the ABI hasn’t (we’re actually putting quite a bit of work into an ABI-compatible upgrade to V8 5.1 in Node core).

I believe doing compilation from a NodeJS version using V8 5.1 should do it, but I see you imply there is not such a version yet, right? I've found https://github.com/nodejs/node/commit/2cc29517966de7257a2f1b34c58c77225a21e05d, but this hasn't been released yet. I'm happy to compile NodeJS from `master` as a temporary solution though, I'll let you know how it goes.

> I have a nodedir setting in my ~/.npmrc, disabling that and then running the setup script again worked for me… lmk if that works (or even applies to you), I guess?

I have no such setting in my `~/.npmrc` sadly :/

> And btw, forcing the build to be done with the same version as Node is a bit strict – ABI/API compatibility is guaranteed over an entire major node version.

I did encounter compilation issues long ago (where add ons compiled with a different -- even slightly -- version were "incompatible"), but that might have been a very particular case. I'll check if its safe to remove that restriction.

> Also, this shouldn’t be related to the version bump in lzma-native… does that sound plausible to you?

Yeah, you're right. I've checkout an older commit in the repo (which uses `npm-shrinkwrap.json`) which reverted this package to an older version and thought that was the case, however didn't notice the electron version was a previous one in that revision as well. Sorry for that!

**Comment by addaleax** [comment]
> I believe doing compilation from a NodeJS version using V8 5.1 should do it, but I see you imply there is not such a version yet, right?

Unfortunately, Node master includes a copy of V8 5.1 that we have modified to be (hopefully!) ABI-compatible with V8 5.0, so that won’t work.

> I have no such setting in my ~/.npmrc sadly :/

Hm – Are you an OS X user? [These lines](https://github.com/resin-io/etcher/blob/master/scripts/build/linux.sh#L76-L84) in the Linux script do the trick for me (i.e. make node-gyp use electron’s own headers, which is the right thing to do here anyway), but there doesn’t seem to be anything similar in the Darwin script.

**Comment by jviotti** [comment]
> Hm – Are you an OS X user? [These lines](https://github.com/resin-io/etcher/blob/master/scripts/build/linux.sh#L76-L84) in the Linux script do the trick for me (i.e. make node-gyp use electron’s own headers, which is the right thing to do here anyway), but there doesn’t seem to be anything similar in the Darwin script.

Indeed, this was the fix, amazing catch. I'm only configuring `npm` in Windows
and GNU/Linux given that this wasn't needed in OS X as far as my
experimentations went.

Thanks a lot for your time and the awesome support, as always. Have a great day!

On Tue, Jul 19, 2016 at 06:20:34PM -0700, Anna Henningsen wrote:
> > I believe doing compilation from a NodeJS version using V8 5.1 should do it, but I see you imply there is not such a version yet, right?
> 
> Unfortunately, Node master includes a copy of V8 5.1 that we have modified to be (hopefully!) ABI-compatible with V8 5.0, so that won’t work.
> 
> > I have no such setting in my ~/.npmrc sadly :/
> 
> Hm – Are you an OS X user? [These lines](https://github.com/resin-io/etcher/blob/master/scripts/build/linux.sh#L76-L84) in the Linux script do the trick for me (i.e. make node-gyp use electron’s own headers, which is the right thing to do here anyway), but there doesn’t seem to be anything similar in the Darwin script.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/addaleax/lzma-native/issues/25#issuecomment-233813132

-- 
Juan Cruz Viotti
Software Engineer

**Comment by addaleax** [comment]
Nice! Btw, if I’m right, that should remove the need to compile with any specific Node version. Also, you may want to add UPX to the list of your (Linux/Windows) dependencies – it’s the only thing I stumbled over while setting etcher up, everything else there was pretty helpful.

Let me know if there’s anything else I can help with!

**Comment by jviotti** [comment]
Thanks a lot for the heads up. I'll get the docs dependencies list in sync with
the build scripts in a moment.

Regarding the specific Node version, you're also right on that one, thanks a
lot again!

On Tue, Jul 19, 2016 at 06:53:10PM -0700, Anna Henningsen wrote:
> Nice! Btw, if I’m right, that should remove the need to compile with any specific Node version. Also, you may want to add UPX to the list of your (Linux/Windows) dependencies – it’s the only thing I stumbled over while setting etcher up, everything else there was pretty helpful.
> 
> Let me know if there’s anything else I can help with!
> 
> ---
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/addaleax/lzma-native/issues/25#issuecomment-233817608

-- 
Juan Cruz Viotti
Software Engineer
