### ISSUE TITLE
Uncaught TypeError: Cannot create property 'checks' on boolean 'false'

### ISSUE THREAD

**Issue by jviotti** [addaleax/lzma-native#26]
Hi,

I'm also encountering this error when starting to make use of `lzma.parseFileIndexFD()`.

This is the code using it:

```js
return fs.openAsync(file, 'r').then((fileDescriptor) => {
  return lzma.parseFileIndexFDAsync(fileDescriptor).tap(() => {
    return fs.closeAsync(fileDescriptor);
  });
});
```

Which results in:

<img width="860" alt="screenshot 2016-07-19 09 24 50" src="https://cloud.githubusercontent.com/assets/2192773/16951403/d262a01c-4d92-11e6-88c9-bb9ad5f012c7.png">

What's also weird is that this only happens on Electron, so maybe its related to: https://github.com/addaleax/lzma-native/issues/25

**Comment by addaleax** [comment]
> so maybe its related to: #25

Yup, has the same cause as it.
