### ISSUE TITLE
Building lzma-native ia32 from x64 in GNU/Linux

### ISSUE THREAD

**Issue by jviotti** [addaleax/lzma-native#27]
I have been trying to build this project from an Ubuntu 16.04 x64 machine targeting ia32.

I first got the following error:

```
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
```

I installed `libc6-dev-i386`, and then got the following error:

```
/usr/include/c++/5/utility:68:28: fatal error: bits/c++config.h: No such file or directory
```

I then installed `g++-multilib`, and got the following errors:

```
/usr/bin/ld: i386:x86-64 architecture of input file `/home/jviotti/Projects/lzma-native/build/liblzma/build/lib/liblzma.a(liblzma_la-common.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/jviotti/Projects/lzma-native/build/liblzma/build/lib/liblzma.a(liblzma_la-index.o)' is incompatible with i386 output
...
/usr/bin/ld: i386:x86-64 architecture of input file `/home/jviotti/Projects/lzma-native/build/liblzma/build/lib/liblzma.a(liblzma_la-crc64_table.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `/home/jviotti/Projects/lzma-native/build/liblzma/build/lib/liblzma.a(liblzma_la-simple_coder.o)' is incompatible with i386 output
collect2: error: ld returned 1 exit status
lzma_native.target.mk:128: recipe for target 'Release/obj.target/lzma_native.node' failed
```

I'm stuck at this point and still investigating...

***

Steps to reproduce:

```sh
git clone https://github.com/addaleax/lzma-native
cd lzma-native
export npm_config_arch=ia32
npm install --build-from-source
```

Thanks a lot!

**Comment by addaleax** [comment]
Hm yeah, this is tricky… installing `libstdc++-6-dev` or `libstdc++-5-dev` and/or setting `export LDFLAGS='-L/usr/lib/gcc/i686-linux-gnu/5/'` and/or `export CFLAGS='-m32'` might help?

That worked for me using gcc 5. gcc 6, which is my default, was being weird, too…

**Comment by jviotti** [comment]
Thanks a lot for the quick response!

I had `libstdc++-5-dev` installed, and `export
LDFLAGS='-L/usr/lib/gcc/i686-linux-gnu/5/'` didn't make any difference,
however `export CFLAGS='-m32` did the trick!

**Comment by addaleax** [comment]
Awesome to hear that! I’m glad I could help. :)

**Comment by jviotti** [comment]
Thanks a lot for the quick response!

I had `libstdc++-5-dev` installed, and `export
LDFLAGS='-L/usr/lib/gcc/i686-linux-gnu/5/'` didn't make any difference,
however `export CFLAGS='-m32` did the trick!

On Wed, Oct 26, 2016 at 10:36:43AM -0700, Anna Henningsen wrote:
> Hm yeah, this is tricky… installing `libstdc++-6-dev` or `libstdc++-5-dev` and/or setting `export LDFLAGS='-L/usr/lib/gcc/i686-linux-gnu/5/'` and/or `export CFLAGS='-m32'` might help?
> 
> That worked for me using gcc 5. gcc 6, which is my default, was being weird, too…
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/addaleax/lzma-native/issues/27#issuecomment-256422155

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jviotti** [comment]
Oops, sorry for the duplicate message. Looks like email responses are getting very delayed!

**Comment by addaleax** [comment]
Don’t worry, I figured something like that happened :)
