### ISSUE TITLE
fallback to local build fails

### ISSUE THREAD

**Issue by redwoz** [addaleax/lzma-native#29]
attempting to install module via npm@3.5.1 / node@6.3.1 fails with the following:

```
5854 verbose stack Error: lzma-native@1.5.2 install: `node-pre-gyp install --fallback-to-build`
5854 verbose stack Exit status 1
5854 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
5854 verbose stack     at emitTwo (events.js:106:13)
5854 verbose stack     at EventEmitter.emit (events.js:191:7)
5854 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
5854 verbose stack     at emitTwo (events.js:106:13)
5854 verbose stack     at ChildProcess.emit (events.js:191:7)
5854 verbose stack     at maybeClose (internal/child_process.js:852:16)
5854 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
5855 verbose pkgid lzma-native@1.5.2
5856 verbose cwd /mnt/rw-a
5857 error Linux 4.9.0-rc6-yocto-standard
5858 error argv "/usr/bin/node" "/usr/bin/npm" "i" "--save" "--verbose" "lzma-native@*"
5859 error node v6.3.1
5860 error npm  v3.5.1
5861 error code ELIFECYCLE
5862 error lzma-native@1.5.2 install: `node-pre-gyp install --fallback-to-build`
5862 error Exit status 1
```

[npm-debug.log.txt](https://github.com/addaleax/lzma-native/files/675528/npm-debug.log.txt)

the host platform is a linux yocto build on kernel 4.9 with build dependencies installed (i am able to install a number of other native modules requiring node-gyp/etc which install/update without issue)

any assistance appreciated!

**Comment by addaleax** [comment]
Unfortunately, `npm` doesn’t include any build output in its debug log… is there any kind of console output here?

**Comment by redwoz** [comment]
no, it appears to be exactly what is in the debug log... is there any way
of making it more verbose?

**Comment by addaleax** [comment]
> is there any way of making it more verbose?

Not really, but the question isn’t as much of how much detail there is as where the build output is written.

Can you try to clone this repository, run `npm install` and (assuming the latter fails) post the output of a manual `node-pre-gyp install --fallback-to-build` run?

**Comment by redwoz** [comment]
suggested process above of cloning repository & running `npm install` from within succeeds without error, however doesn't appear to _build_ anything.

however:
- the manual `node-pre-gyp install --fallback-to-build` fails due to the make command including `-I /usr/lib/node_modules/node-gyp/addon.gypi` which doesn't exist (overcome by manually running `npm install node-gyp` from `/usr/lib`)
- overcome the next hurdle of node missing `nan` library by running `npm install nan` from current dir
- latest logfile since, which still fails build [npm-debug.log.txt](https://github.com/addaleax/lzma-native/files/676971/npm-debug.log.txt)

i have been historically locked to node@6.3.1 and npm@3.5.1, not sure whether attempting to install using latest could help...

**Comment by addaleax** [comment]
> overcome the next hurdle of node missing `nan` library by running `npm install nan` from current dir

That’s odd, `npm` should definitely install all dependencies (including `nan`).

> latest logfile since, which still fails build [npm-debug.log.txt](https://github.com/addaleax/lzma-native/files/676971/npm-debug.log.txt)

Again, the console output is probably quite a bit more interesting than the debug log. :/

There’s a
```
gyp: Call to 'sh liblzma-config.sh "/mnt/rw-b/lzma-native/build" "/mnt/rw-b/lzma-native/deps/xz-5.2.1.tar.bz2"' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
```
line in your debug log – what happens when you run that command (`sh liblzma-config.sh "/mnt/rw-b/lzma-native/build" "/mnt/rw-b/lzma-native/deps/xz-5.2.1.tar.bz2"`) manually?

> i have been historically locked to node@6.3.1 and npm@3.5.1, not sure whether attempting to install using latest could help...

I wouldn’t know of any significant changes in Node, node-gyp or npm that would affect the install/build process, so, probably not.

(Sorry for the late reply, there was a new year’s eve in the way. Happy new year!)

**Comment by redwoz** [comment]
@addaleax the process i've used to finally get this working:

- ensured `bzip2` is installed on the rootfs, as it is a dependency for `liblzma-config.sh`
- manually installed dependency `nan`, `node-gyp` & `node-pre-gyp` as these either don't exist or aren't correctly referenced/addressed by build scripts

happy to provide additional testing if you decide to update.

no problems with the late reply and happy new year =)

**Comment by addaleax** [comment]
Yeah, right, bzip2 is a dependency for compiling right now. Maybe that’s something that could be changed, but tbh, I would expect that to be installed on most systems. I’ll just leave it at “I’ll give that advice to whoever comes across this problem” for now, this can still be revisited if it pops up more frequently.
