### ISSUE TITLE
Invalid HTTPS cert on entless.org preventing node-pre-gyp precompiled binary fetches

### ISSUE THREAD

**Issue by YLivay** [addaleax/lzma-native#34]
Yo, it's that time of the year when we bug you again :)

According to the log lines in our CI, downloading the precompiled binary with node-pre-gyp fails:
```
node-pre-gyp ERR! Tried to download: https://node-pre-gyp.entless.org/lzma-native/lzma_native-v1.5.2-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@1.5.2 and node@6.9.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
```
Visiting the url manually shows the following cert error: NET::ERR_CERT_COMMON_NAME_INVALID
Thanks a ton for the awesome library, we've been happily using it for around a year :)

**Comment by addaleax** [comment]
Should be fixed now, thanks for the ping :)

**Comment by YLivay** [comment]
That was insanely fast, thank you!
