### ISSUE TITLE
Prebuilt for node 8

### ISSUE THREAD

**Issue by develar** [addaleax/lzma-native#37]
Could you please publish for ABI 57? https://github.com/nodejs/node/commit/ec7cbaf266

**Comment by addaleax** [comment]
Yeah, thanks for the reminder. I had started working on that a bit ago but CI gave me headaches; the builds seem to be passing now so I’ll push 2.0.3 out in ~2 hours (because, yes, that’s how long CI takes).

**Comment by addaleax** [comment]
`+ lzma-native@2.0.3`

Let me know if you have any trouble.

**Comment by develar** [comment]
> $ node --version

v8.1.2

>  yarn add lzma-native

Actually I see that compilation is performed on my macOS.

But, on clean Win10 machine (without dev env, visual studio and so on) I see " is installed via remote" and all is ok. Thanks!
