### ISSUE TITLE
Remove dev files after build

### ISSUE THREAD

**Issue by develar** [addaleax/lzma-native#38]
Currently, prebuild binaries doesn't work for macOS. And it leads to https://github.com/electron-userland/electron-builder/issues/1738

I have fixed this issue on electron-builder side to help users (https://github.com/develar/electron-builder/commit/fe42d8e5715eb1c2bfffe72693cdb358c7b9ab1d#diff-521d2ecafaba778a4744b243eee6a02cR135), but will cool if in the install script after build all files that not required for production, will be removed.

**Comment by addaleax** [comment]
> Currently, prebuild binaries doesn't work for macOS

That has been fixed, see #39. Is that sufficient to solve your problem in the majority of cases?

But yes, what you’re asking for seems to make sense.

**Comment by develar** [comment]
> s that sufficient to solve your problem in the majority of cases?

Electron can have own ABI version. Sorry, I cannot yet provide ABI version matrix.

**Comment by addaleax** [comment]
@develar Okay, I’ve published 3.0.0 with the build dir removed after install, and prebuilt binaries for Electron 1.6/1.7 on macOS and x64 Linux. Again, let me know if you have any trouble. :)
