### ISSUE TITLE
missing install dependency rimraf

### ISSUE THREAD

**Issue by redwoz** [addaleax/lzma-native#43]
looks like there's a dependency on `rimraf` for this module which, for some reason in my case, isn't being installed as part of the build - any idea why or how we can get this fixed?

```
  SOLINK_MODULE(target) Release/obj.target/lzma_native.node
  COPY Release/lzma_native.node
  COPY /mnt/rw-a/node_modules/lzma-native/binding-v3.0.1-node-v51-linux-arm/lzma_native.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/mnt/rw-a/node_modules/lzma-native/build'
module.js:472
    throw err;
    ^

Error: Cannot find module '/mnt/rw-a/node_modules/lzma-native/node_modules/rimraf/bin.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

npm ERR! Linux 4.9.4-yocto-standard
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! lzma-native@3.0.1 install: `node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build`
npm ERR! Exit status 1
```

using `npm install lzma-native` on a yocto embedded linux build, and installing rimraf by itself succeeds.

**Comment by addaleax** [comment]
That’s really odd, `rimraf` should even be contained in lzma-native’s tarball for 3.0.1. Do you use a non-standard npm registry? Does upgrading node or npm help (Node 7 is unmaintained since end of June)?

**Comment by redwoz** [comment]
- using standard npm
- unable to upgrade node/npm yet until https://github.com/imyller/meta-nodejs is updated (i'll try this as soon as its available)

note that the node-pre-gyp binary isn't downloaded due to 404 and triggers fallback to build:
`node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v51-linux-arm.tar.gz`


note that the following works ok:
```
git clone https://github.com/addaleax/lzma-native
cd lzma-native/
npm install nan node-pre-gyp readable-stream rimraf
node_modules/node-pre-gyp/bin/node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build
```

**Comment by addaleax** [comment]
> note that the node-pre-gyp binary isn't downloaded due to 404 and triggers fallback to build:

That should be expected for `arm`, and it’s probably nothing I can do sth about unless you happent o know free CI providers supporting that arch?

> note that the following works ok:

Yeah, I would expect that. The question is why `npm install lzma-native` – or whatever similar thing you are running – doesn’t unpack `lzma-native` the way it is uploaded in the registry.
