### ISSUE TITLE
No node-pre-gyp precompiled binary for ARM?

### ISSUE THREAD

**Issue by bhjelstrom** [addaleax/lzma-native#44]
https://node-pre-gyp.entless.org/lzma-native/lzma_native-v1.5.2-node-v48-linux-arm.tar.gz gives a 404.

Thanks

**Comment by addaleax** [comment]
I’d need access to CI machines for ARM to be able to support it, sorry. Unless you have any suggestions for that, there might not be much I can do here …

**Comment by Gigakaiser** [comment]
Got it. I found a work-around, but thank you for the your fast response.

**Comment by patrickllanes** [comment]
@bhjelstrom Hello, I'm having issues building for an ARM device and I was curious as to what your workaround for it was. Can you shoot me an email at your earliest convenience? My email is patrickl@golighthouse.com. Thank you
