### ISSUE TITLE
lzma_native-v3.0.2-node-v59-win32-x64.tar.gz not found

### ISSUE THREAD

**Issue by akbarharyadi** [addaleax/lzma-native#47]
Hey there,
I'm using win 10 pro 64x.
when I try run yarn upgrade, I got error : 

> yarn install v0.27.5
> info No lockfile found.
> [1/4] Resolving packages...
> warning react-native > connect@2.30.2: connect 2.x series is deprecated
> [2/4] Fetching packages...
> warning fsevents@1.1.3: The platform "win32" is incompatible with this module.
> info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "mobx-react@4.3.5" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
> [4/4] Building fresh packages...
> [-/3] ⠁ waiting...
> [2/3] ⠁ lzma-native: LINK : fatal error LNK1104: cannot open file 'F:\ReactApp\mPos\node_modules\lzma-native\deps\doc\liblzma.def' [F:\ReactApp\mPos\node_modules\lzma-native\build\liblzma.vcxpr
> [-/3] ⠁ waiting...
> [-/3] ⠁ waiting...
> error F:\ReactApp\mPos\node_modules\lzma-native: Command failed.
> Exit code: 1
> Command: C:\Windows\system32\cmd.exe
> Arguments: /d /s /c node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build
> Directory: F:\ReactApp\mPos\node_modules\lzma-native
> Output:
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.39
> node-pre-gyp info using node@9.2.0 | win32 | x64
> node-pre-gyp info check checked for "F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64\lzma_native.node" (not found)
> node-pre-gyp http GET https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.2-node-v59-win32-x64.tar.gz
> node-pre-gyp http 404 https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.2-node-v59-win32-x64.tar.gz
> node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.2-node-v59-win32-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.2 and node@9.2.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
> node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.2-node-v59-win32-x64.tar.gz
> 
> F:\ReactApp\mPos\node_modules\lzma-native>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else
> (node "" clean )
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.6.2
> gyp info using node@9.2.0 | win32 | x64
> gyp info ok
> 
> F:\ReactApp\mPos\node_modules\lzma-native>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fa
> llback-to-build --module=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64\lzma_native.node --module_name=lzma_native --module_path=F:\ReactApp\mPos\node_modules\lzma-native\bi
> nding-v3.0.2-node-v59-win32-x64 --python=python2.7 --msvs_version=2015 )  else (node "" configure --fallback-to-build --module=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64
> \lzma_native.node --module_name=lzma_native --module_path=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64 --python=python2.7 --msvs_version=2015 )
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.6.2
> gyp info using node@9.2.0 | win32 | x64
> gyp info spawn C:\Python27\python.exe
> gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'msvs',
> gyp info spawn args   '-G',
> gyp info spawn args   'msvs_version=2015',
> gyp info spawn args   '-I',
> gyp info spawn args   'F:\\ReactApp\\mPos\\node_modules\\lzma-native\\build\\config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\Akbar Haryadi\\.node-gyp\\9.2.0\\include\\node\\common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Akbar Haryadi\\.node-gyp\\9.2.0',
> gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
> gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Akbar Haryadi\\.node-gyp\\9.2.0\\<(target_arch)\\node.lib',
> gyp info spawn args   '-Dmodule_root_dir=F:\\ReactApp\\mPos\\node_modules\\lzma-native',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'F:\\ReactApp\\mPos\\node_modules\\lzma-native\\build',
> gyp info spawn args   '-Goutput_dir=.' ]
> Warning: Missing input files:
> F:\ReactApp\mPos\node_modules\lzma-native\build\..\deps\bin_x86-64\liblzma.dll
> F:\ReactApp\mPos\node_modules\lzma-native\build\..\deps\doc\liblzma.def
> gyp info ok
> 
> F:\ReactApp\mPos\node_modules\lzma-native>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallba
> ck-to-build --module=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64\lzma_native.node --module_name=lzma_native --module_path=F:\ReactApp\mPos\node_modules\lzma-native\bindin
> g-v3.0.2-node-v59-win32-x64 )  else (node "" build --fallback-to-build --module=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64\lzma_native.node --module_name=lzma_native --m
> odule_path=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64 )
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.6.2
> gyp info using node@9.2.0 | win32 | x64
> gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
> gyp info spawn args [ 'build/binding.sln',
> gyp info spawn args   '/clp:Verbosity=minimal',
> gyp info spawn args   '/nologo',
> gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   build
>   Microsoft (R) Library Manager Version 14.00.24210.0
>   Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> LINK : fatal error LNK1104: cannot open file 'F:\ReactApp\mPos\node_modules\lzma-native\deps\doc\liblzma.def' [F:\ReactApp\mPos\node_modules\lzma-native\build\liblzma.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
> gyp ERR! System Windows_NT 10.0.15063
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=F:\\ReactApp\\mPos
> \\node_modules\\lzma-native\\binding-v3.0.2-node-v59-win32-x64\\lzma_native.node" "--module_name=lzma_native" "--module_path=F:\\ReactApp\\mPos\\node_modules\\lzma-native\\binding-v3.0.2-node-v59-win32-
> x64"
> gyp ERR! cwd F:\ReactApp\mPos\node_modules\lzma-native
> gyp ERR! node -v v9.2.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64\lzma_native.node --module_na
> me=lzma_native --module_path=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\ReactApp\mPos\node_modules\lzma-native\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> node-pre-gyp ERR! System Windows_NT 10.0.15063
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\ReactApp\\mPos\\node_modules\\lzma-native\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd F:\ReactApp\mPos\node_modules\lzma-native
> node-pre-gyp ERR! node -v v9.2.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok
> Failed to execute 'node-gyp.cmd build --fallback-to-build --module=F:\ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64\lzma_native.node --module_name=lzma_native --module_path=F:
> \ReactApp\mPos\node_modules\lzma-native\binding-v3.0.2-node-v59-win32-x64' (1)
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I think https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.2-node-v59-win32-x64.tar.gz link si problem, because 404.

**Comment by addaleax** [comment]
I’ve added CI support for Node 9, this should work with `lzma-native@3.0.3` now. Let me know if you run into any more trouble!
