### ISSUE TITLE
Trying to use this with AWS lambda

### ISSUE THREAD

**Issue by simlu** [addaleax/lzma-native#52]
Runs locally and I'm compiling with Ubuntu 16.04 and it *should* work, however I'm getting an unhelpful error message that a file import fails.

Anyone else have any luck with this?

**Comment by addaleax** [comment]
@simlu I am not too familiar with AWS lambda, but if you have a .zip or something that I could try out I’d be happy to.

**Comment by simlu** [comment]
My bad. AWS Lambda Linux Distro and Ubuntu used to be compatible, but they're not anymore. Following this to the letter worked for me: https://instil.co/2017/08/07/using-native-dependencies-with-aws-lambda/
