### ISSUE TITLE
Error on decoding damaged archives

### ISSUE THREAD

**Issue by dubsky** [addaleax/lzma-native#53]
When I try to decompress an archive which I intentionally damaged, I get an uncaught exception. My code is something like this:

lzma.decompress(lzmaData, (result) => {
                if(result===null) {
                    console.log('bad data');
                    callback(null,null);
                    return;
                }
....
            });

The callback gets never called.

Uncaught Exception Cannot read property 'code' of null
W20180221-12:05:26.186(1)? (STDERR) TypeError: Cannot read property 'code' of null
W20180221-12:05:26.187(1)? (STDERR)     at JSLzmaStream._transform (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/index.js:175:25)
W20180221-12:05:26.187(1)? (STDERR)     at JSLzmaStream._flush (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/index.js:196:10)
W20180221-12:05:26.187(1)? (STDERR)     at JSLzmaStream.<anonymous> (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_transform.js:138:49)
W20180221-12:05:26.187(1)? (STDERR)     at Object.onceWrapper (events.js:313:30)
W20180221-12:05:26.187(1)? (STDERR)     at emitNone (events.js:106:13)
W20180221-12:05:26.187(1)? (STDERR)     at JSLzmaStream.emit (events.js:208:7)
W20180221-12:05:26.187(1)? (STDERR)     at prefinish (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_writable.js:596:14)
W20180221-12:05:26.187(1)? (STDERR)     at finishMaybe (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_writable.js:604:5)
W20180221-12:05:26.187(1)? (STDERR)     at afterWrite (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_writable.js:470:3)
W20180221-12:05:26.187(1)? (STDERR)     at onwrite (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_writable.js:461:7)
W20180221-12:05:26.188(1)? (STDERR)     at WritableState.onwrite (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_writable.js:169:5)
W20180221-12:05:26.188(1)? (STDERR)     at afterTransform (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_transform.js:104:3)
W20180221-12:05:26.188(1)? (STDERR)     at JSLzmaStream.TransformState.afterTransform (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/node_modules/readable-stream/lib/_stream_transform.js:79:12)
W20180221-12:05:26.188(1)? (STDERR)     at Immediate.setImmediate (/home/vlada/Projects/trip-market-ng/tmn-client-web/node_modules/lzma-native/index.js:87:36)
W20180221-12:05:26.188(1)? (STDERR)     at runCallback (timers.js:789:20)
W20180221-12:05:26.188(1)? (STDERR)     at tryOnImmediate (timers.js:751:5)
W20180221-12:05:26.188(1)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:722:5)
=> Exited with code: 1

**Comment by addaleax** [comment]
Can you share a reproduction and/or tell me which version of this library you are using?

**Comment by dubsky** [comment]
I am using 3.0.4. I tried to find out what the problem is and it seems that

1) error is detected
2) based on that the cleanup event is raised
3) one part of the cleanup is to nullify JSLzmaStream.nativeStream.
4) the error I got has been raised from JSLzmaStream._transform as if the stream continues to be decoded even when error has been detected previously
5) operations on previously nullfied JSLzmaStream.nativeStream fail...

**Comment by dubsky** [comment]
Put this into a file and run it using node. I have tried to add it into tests but mocha swallows the error and pretends everything went fine.

`var lzma=require('lzma-native');

        var BananasCompressed = '/Td6WFoAAAFpIt42AgAhARYAAAB0L+Wj4AlIAoNdAD2IiGeUEJx+XyPe9zlKy8Fq9NRkkIL92DhFSBQg7aCu7q0WnisV5e/m3wZEjrETvRqJKS6Gw17x5Olk1NaiT5PSDDTMsPlwPPc3sY3Jx4qHvuf03GV9wV7MaFX8w9lZcwReK7EATPCMK6uRlausTqXtzqtWbm47a7GVnJH3wfqsnDYPqGr07CH0BddY3g1r6OQe9TDl44fCbZa2Pfv2d4PYqxvQQE8Wdx9wjG+HSc9b87tkI4zdPWvnVyNZLP1oy5GCjwRynslfZDBkID2nnUVXGi9BvZ03lNpBfb32DVK0ymSVH0LPK2yMD2gXQmd0aHutzRF9owqiA9Me6/Adzvt5ezVhYesonDz02OA9pOSpARSmbeYRSoiBWiFTG7AB3LLiAaeMNwuKXqN2zuYozX/LpjRUAYT99OYkmDvXZehbS4o8WzanJcg2r+rc6Ik3FKbe2CsUx7nZHNZ7pverwiRlwJgjjCQ16qYAsaKaLN8LJSdSrY0deh8q2ev4Z5t8BNUQBWEq4D4ExDyhgYcjueF9/LWmgHoAJDQiCebSxXFV5ywmrBwbR2Nr9kq/Lo6FDAFg4OxoxI2ZXuj7pO+P/hgUVx6M6ciwu3YpM61MdHoct5Jkd9867IXmc/sYBRTGUgrNnBVHWBDCzekoeUY3L0HWu4k2URac20olIGZOY10i8nMEP1C0cUTIO/E14QZMwralM7/shbyn66w2Fy6rXN089xXReYoKomp/ye3cI2cUfgEcnT+lcsdByHEa1hC08oQzD0jHQIEYkZibuj5BSM21cuiAUtoRT9f0Ogpv+5VLwgrKYikTF6nPUmwKkTvwYi3jBeWLHG80fVAKsSaR415ppoAACO2mKIAAZsFyRIAAL9r82g+MA2LAgAAAAABWVg==';
                lzma.decompress(Buffer.from(BananasCompressed, 'base64'), function(result,r2) {
                    console.log(result);
                    console.log(r2);
                });


setTimeout(function() {
}, 5000);`

**Comment by addaleax** [comment]
Okay, this should have been fixed in `lzma-native@3.0.5`. Let me know if you need anything else!

**Comment by dubsky** [comment]
Thank you for the prompt resolution of the problem. (And for creating and maintaining the library of course).

I patched my project exactly as you fixed this, I just suspected that this way the stream with the archive data is read up to its end instead of stopping immediately after the error.
