### ISSUE TITLE
Missing native binaries for Electron on Windows

### ISSUE THREAD

**Issue by TheFeelTrain** [addaleax/lzma-native#69]
Why are there no pre-built binaries for Electron on Windows?

I am specifically looking for `lzma_native-v4.0.2-electron-v2.0-win32-x64`

Thanks!

**Comment by leshow** [comment]
You can compile these yourself following https://electronjs.org/docs/tutorial/using-native-node-modules

follow 'using npm'. I have an electron app that uses lzma-native
