### ISSUE TITLE
lzma.createCompressor causes node process to stop immediately

### ISSUE THREAD

**Issue by mattpen** [addaleax/lzma-native#78]
```
$ node --version
v8.9.4

$ npm --version
5.1.0

$ npm i lzma-native

> lzma-native@4.0.3 install C:\Users\matt\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[lzma-native] Success: "C:\Users\matt\node_modules\lzma-native\binding-v4.0.3-node-v57-win32-x64\lzma_native.node" is installed via remote
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\matt\package.json'
npm WARN matt No description
npm WARN matt No repository field.
npm WARN matt No README data
npm WARN matt No license field.

+ lzma-native@4.0.3
added 68 packages in 6.401s

$ node
> const lzma = require('lzma-native')
undefined
> lzma.createCompressor()

$
```

I'm trying to install lzma-native on a Windows 10 machine using MinGW/Git Bash.    The library seems to install successfully, but when I call createCompressor it causes the node process to fail immediately.  I can't even catch the error with a try/catch block.  Any idea how I can fix this?  I'm not so concerned if it isn't compatible with Windows, but it would be ideal if I can detect whether it will fail or recover from a failure.

NOTE: It works just fine on the same machine using WSL.

**Comment by addaleax** [comment]
That is super weird… I’ll try to look into that, but if you can debug it too, that would be helpful. Generally, this library has Windows support, is tested on Windows in CI and I haven’t head about an issue like this before.

One thing you could always try is to use an up-to-date version of Node.js (the latest v8.x, or generally a newer version), and see if it still reproduces?

**Comment by mattpen** [comment]
I upgraded to the latest LTS - node v10.15.3 & npm v5.1.0 and this problem is no longer occurring.  Thanks for the quick response!
