### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by tttedu304** [addaleax/lzma-native#84]
Hey, I've been trying to install some stuff through npm, this stuff seems to need node-gyp, or I don't know. But I'm not able to install anything since I keep getting a lot of errors, I don't know what else to do, this is the error I got, I hope someone can help me.

root@lio:~/Tohka-Network# npm i quick.db

> integer@2.1.0 install /root/Tohka-Network/node_modules/integer
> node-gyp rebuild

make: Entering directory '/root/Tohka-Network/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
  SOLINK_MODULE(target) Release/obj.target/integer.node
  COPY Release/integer.node
  COPY ../build/integer.node
  TOUCH Release/obj.target/place_resulting_binary.stamp
make: Leaving directory '/root/Tohka-Network/node_modules/integer/build'

> lzma-native@3.0.8 install /root/Tohka-Network/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@11.13.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v67-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@11.13.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
gyp: Call to 'sh liblzma-config.sh "/root/Tohka-Network/node_modules/lzma-native/build" "/root/Tohka-Network/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/root/.nvm/versions/node/v11.13.0/bin/node" "/root/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64"
gyp ERR! cwd /root/Tohka-Network/node_modules/lzma-native
gyp ERR! node -v v11.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v11.13.0/bin/node /root/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/Tohka-Network/node_modules/lzma-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1001:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
node-pre-gyp ERR! System Linux 4.9.0-8-amd64
node-pre-gyp ERR! command "/root/.nvm/versions/node/v11.13.0/bin/node" "/root/Tohka-Network/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/Tohka-Network/node_modules/lzma-native
node-pre-gyp ERR! node -v v11.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/root/.nvm/versions/node/v11.13.0/bin/node /root/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64' (1)
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN enmap@4.8.7 requires a peer of better-sqlite-pool@github:eslachance/better-sqlite-pool but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@3.0.8 install: `node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@3.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-13T15_04_37_384Z-debug.log
root@lio:~/Tohka-Network# gyp: Call to 'sh liblzma-config.sh "/root/Tohka-Network/node_modules/lzma-native/build" "/root/Tohka-Network/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/root/.nvm/versions/node/v11.13.0/bin/node" "/root/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/root/Tohka-Network/node_modules/lzma-native/binding-v3.0.8-node-v67-linux-x64"
gyp ERR! cwd /root/Tohka-Network/node_modules/lzma-native
gyp ERR! node -v v11.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by Pixcell** [comment]
@tttedu304 Im running into the same kind of issues, although it's a different version of lzma-native.

Could you please give me some hints on how you resolved your issues? Thank you

**Comment by iccry** [comment]
The supported version is node11. Check the node version。
