### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by c43721** [addaleax/lzma-native#85]
https://github.com/jdeurt/payload-rewrite
trying to rehost this project, but npm keeps failing:
Log file:
[2019-11-04T01_53_30_009Z-debug.log](https://github.com/addaleax/lzma-native/files/3802488/2019-11-04T01_53_30_009Z-debug.log)

I've exhausted every search possible and I think it's because it's trying to download a version that's not on the website anymore.

i dont know specifically if it's lzma related.
hopefully this is still read :|

**Comment by addaleax** [comment]
@c43721 Your debug log is missing the actual error output, so it’s not very useful. Can you share that from e.g. stderr?

**Comment by c43721** [comment]
@addaleax I will get that sorted tomorrow.

**Comment by c43721** [comment]
Ok, it's been a bit. Was doing some stuff.

Here's the error that keeps popping up:
![Capture](https://user-images.githubusercontent.com/55610086/68983001-b59f6100-07ce-11ea-8937-e5b7b5bfa0bf.JPG)

This link: https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v72-win32-ia32.tar.gz

The link isn't valid, which is where im confused. But it can't be from lzma, because npm install windows-build-tools fails as well, and canvas fails too. 
I am on windows which is probably why it's failing tbh.

**Comment by addaleax** [comment]
The build situation here has improved a lot with `lzma-native@6.0.0` which brings N-API support to this module. Let me know if you have further trouble, but for now I’m closing this issue.
