### ISSUE TITLE
Prebuilt binaries issue on CentOS 7

### ISSUE THREAD

**Issue by jeanbmar** [addaleax/lzma-native#88]
I'm unable to run lzma-native on CentOS 7 using Node.js 12.13 (npm install works fine).
I get the following error:

> /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/src/clash-js/node_modules/lzma-native/binding-v5.0.0-node-v72-linux-x64/lzma_native.node)

It seems to be a GCC version issue, CentOS 7 using GCC 4.8.5.
``strings /lib64/libstdc++.so.6 | grep CXXABI``

> CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1

**Comment by jeanbmar** [comment]
As a work around I run ``npm rebuild lzma-native --build-from-source`` after my whole project install

**Comment by addaleax** [comment]
@jeanbmar Is that an issue you’re having with other native modules too? Does this also happen when installing versions prior to 5.0.0?

We’ve had issues with this for the Node.js Linux builds too, I think, where the solution was to build on CentOS as the lowest supported ABI version; however, that’s not really an option here for me.

**Comment by jeanbmar** [comment]
I have no other native module on this project to test unfortunately.
I just tried with version 4.0.6 and it's working fine with the prebuilt binaries.
The module is also working fine when I build 5.0.0 locally instead of using prebuilt binaries.

I think the easiest way to solve things here would be to prevent CentOS matching with the prebuilt binaries, but my knowledge on this topic is too limited to make further suggestions.

**Comment by addaleax** [comment]
> I think the easiest way to solve things here would be to prevent CentOS matching with the prebuilt binaries, but my knowledge on this topic is too limited to make further suggestions.

Mine too :)

I’ll try downgrading back to gcc 4.9 for the Travis CI builds, maybe that helps. It’ll take a short while for the builds to compile, though.

**Comment by addaleax** [comment]
@jeanbmar Can you try v5.0.1?

**Comment by jeanbmar** [comment]
It's working. Thank you!

**Comment by addaleax** [comment]
:tada:
