### ISSUE TITLE
LZMA().decompress returns null

### ISSUE THREAD

**Issue by Oen44** [addaleax/lzma-native#92]
There is a old software that reads 2 files and decompresses them using LZMA (not LZMA2). It's written in Adobe AIR, using buildin utils to work on ByteArray. Here is a function that uses [uncompress](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/ByteArray.html#uncompress()) method.
```as
        public function decode(bytes:ByteArray):ThingData
        {
            if (!bytes)
                throw new NullArgumentError("bytes");

            bytes.position = 0;
            bytes.endian = Endian.LITTLE_ENDIAN;
            bytes.uncompress(CompressionAlgorithm.LZMA);

            var version:uint = bytes.readUnsignedShort();
            if (version == OBDVersions.OBD_VERSION_2)
                return decodeV2(bytes);
            else if (version >= 710) // OBD version 1: client version in the first two bytes.
                return decodeV1(bytes);
            else
                throw new Error(StringUtil.format("Invalid OBD version {0}", version));
        }
```

I'm loading same files using File System and `LZMA().decompress` to "uncompress" them, however returned data is always `null`.
```js
const express = require('express')
const fs = require('fs')
const lzma = require('lzma-native')

const app = express()
const port = 3000

app.listen(port, () => {
    fs.readFile("First.dat", null, (err, data) => {
        lzma.LZMA().decompress(data.buffer, (decompressedResult) => {
            console.log(decompressedResult) // null
        });
    })
})
```
I'm attaching one of the files (2nd is around 170MB).
[First.zip](https://github.com/addaleax/lzma-native/files/4668401/First.zip)

**Comment by Oen44** [comment]
>     * The `decompress()` function here takes a second argument that provides the error, if one occurred. In this case, that is `LZMA_FORMAT_ERROR: File format not recognized`.
>     * If I unpack `First.zip` as attached by you here and run `lzma --lzma1 -d < First.dat` on the command line, that fails similarly.
Why is that? How is it that one algorithm for the same compression method works but not the other?

>     * You should not be using `data.buffer` here – `data` is the right thing to use. A Node.js `Buffer` does not need to have a 1:1 correspondence to the underlying `ArrayBuffer`.
Tried just `data` too, same results.

So this means that lzma-native won't work here? I can't find anything to work with these files...

**Comment by addaleax** [comment]
@Oen44 I don’t know. Whatever `First.dat` is, it is not an LZMA file, so no, lzma-native won’t be able to decompress it.

Looking at the file directly, it seems like there are lots of strings and null bytes in there, which are good indications that it’s just an uncompressed raw data file.

**Comment by Oen44** [comment]
@addaleax  Explain this part then `bytes.uncompress(CompressionAlgorithm.LZMA);`

**Comment by addaleax** [comment]
@Oen44 It’s literally not my job, in any way, to figure out how *your* code works.
