### ISSUE TITLE
Pre-built binaries not found for lzma-native@5.0.1 and node@14.15.3

### ISSUE THREAD

**Issue by TeamPopplio** [addaleax/lzma-native#95]
# Usage
I'm developing an [application](https://github.com/YTP-Plus/YTPPlusCLI) that takes advantage of [ffmpeg-cli](https://github.com/PotatoParser/ffmpeg-cli) and its requirement is lzma-native.

# Problem

```
C:\Users\DONT_\Documents\YTPPlus\YTPPlusCLI>npm install

> lzma-native@5.0.1 install C:\Users\DONT_\Documents\YTPPlus\YTPPlusCLI\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v5.0.1-node-v83-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for lzma-native@5.0.1 and node@14.15.3 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
```

# Details

I'm using NodeJS ``v14.15.3`` on Windows 10 and the end-users for the application in question cannot install it due to requiring a source compile, which isn't bundled with NodeJS unless you specifically choose to install the tools to do so during installation.

This results in an error for those who can't source compile.

# Resolution

I cannot say for certain what could resolve this but I have learned that there aren't any versions for ``node-v83`` hosted. I would appreciate it if this could be resolved on the server's end if possible.

# Conclusion

Due to requiring a source compilation as of now, I have resorted to distributing my own binaries to resolve the issue temporarily. It would be helpful if my NodeJS version was supported as that is my target for the application.

Please let me know if there are any questions.

Thank you.

**Comment by addaleax** [comment]
Using `lzma-native@6.x` should solve this – the newer binaries are independent of Node.js (or Electron) versions.
